### ISSUE TITLE
Wizyty tylko z jednego dnia

### ISSUE THREAD

**Issue by bonk1990** [apqlzm/medihunter#10]
Czy aplikacja zwraca tylko wizyty z jednego dnia? Oczywiście tego, który jest najbliżej daty od której się szuka?

Przykładowo jeśli pojawi się dogodny dla mnie termin na 3 stycznia, ale wciąż dostępna jest wizyta na 2 stycznia (godzina mi nie odpowiada) to aplikacja mnie o tym nie poinformuje?

**Comment by apqlzm** [comment]
Dodałem zmiany umożliwiające wyświetlenie wyników dla więcej niż jednego dnia.
Wystarczy teraz dodać opcję `-j x` gdzie x oznacza liczbę dni. 

Na przykład gdy ustawimy `-j 3` oznaczać to będzie że skrypt odszuka najbliższe trzy dni w których są wolne terminy. Jest to równoznaczne z wciśnięciem przycisku `Szukaj` i dwukrotnym `Pokaż więcej`.

**Comment by bonk1990** [comment]
Świetna robota.
Edit: a może lepszym pomysłem byłoby żeby pokazywało wszystkie wizyty w danym zakresie dat?

**Comment by apqlzm** [comment]
Poprawiłem działanie opcji `--end-date` tak aby skrypt pokazywał wszystkie dostępne wizyty w przedziale między `--start-date` i `--end-date`. Tak więc teraz zamiast podawać `-j x` można podać datę końcową.
