### ISSUE TITLE
Unsuccessful logging in

### ISSUE THREAD

**Issue by Rexikon** [apqlzm/medihunter#13]
Używam:
medihunter my-plan --user moj_login --password moje_haslo
Dostaje:
Unsuccessful logging in

Jakiś pomysł czemu tak?

**Comment by pkobielak** [comment]
Hej @Rexikon,
Mam ten sam problem, jak go rozwiązałeś?
@apqlzm Upewniłem się że dane logowania są poprawne, a wersja python'a powyżej 3.6.

**Comment by apqlzm** [comment]
Być może zmieniło się coś w systemie Medicover i logowanie przestało działać. Otworzyłem nowy issue  #14 Postaram się niedługo na to zerknąć.
