### ISSUE TITLE
Impossible to skip phone "visits"

### ISSUE THREAD

**Issue by jjarmolowicz** [apqlzm/medihunter#17]
By default medicover is returning visits over phone in search results. Would be cool to skip them as they are useless when looking for visit with required physical presence.

**Comment by jjarmolowicz** [comment]
I can create a PR, i have a code ready but I'm missing a write access.

**Comment by apqlzm** [comment]
To contribute to a repository without write access you need to create a fork and then create PR from that fork. This could be helpful https://gist.github.com/dlaehnemann/e6c8f46eee80112267af70ae92a3df13

**Comment by jjarmolowicz** [comment]
yeah I forgot how to work on github :) Will do.
