### ISSUE TITLE
Medihunter started to error: `Unsuccessful logging in`

### ISSUE THREAD

**Issue by mwoz123** [apqlzm/medihunter#32]
First of all @apqlzm  - thanks for great project:) I use it for long time :)

Today I noticed that `medihunter` stopped working for me :(

```bash
$ /usr/bin/python3 medihunter.py find-appointment -r 205 -s 27160 --user $CARD_S --password $PASS_S
Unsuccessful logging in
marcin@OpenWrt:~/medihunter-old$ 
```

I tried on 2 accounts both are logging same error, and it was working 3 days ago. 

Same issue on second computer.

Was there a change in mediover logic / did they banned medihunter :( ?

**Comment by robertnowak** [comment]
Hi! I'm also a fan of medihunter :) Changing user_agent value in https://github.com/apqlzm/medihunter/blob/df10057302cd7edb6af73f3e1e8d6600124e8364/medicover_session.py#L17 helped. I've used 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
```

**Comment by mwoz123** [comment]
Works :) Thanks a lot Robert :)

**Comment by piomar123** [comment]
@robertnowak Same issue here. Maybe create a PR with this update?

**Comment by robertnowak** [comment]
@piomar123 I don't have write access as I'm not a contributor :(

**Comment by piomar123** [comment]
@robertnowak Just fork it in your account, push the changes and create a PR :)
Or for such small charge you can edit directly from web UI and it will suggest to create the PR :)

**Comment by apqlzm** [comment]
Thanks for reporting the issue. It should be fixed as User-Agent is now randomly generated.
