### ISSUE TITLE
Jak aktywować powiadomienia?

### ISSUE THREAD

**Issue by mikebike87** [apqlzm/medihunter#46]
Jestem początkujący i mam problem z uruchomieniem powiadomień w medihunter.py

Co dokładnie powinienem zrobić z komendami 
# bash
export NOTIFIERS_PUSHOVER_TOKEN=avykwnqc8ohyk73mo1bsuggsm3r4qf
export NOTIFIERS_PUSHOVER_USER=s4g1zoewbzseogp4knrapx23k9yi95

Próbowałem je wpisać do kodu w medihunter.py lub wykonać w terminalu osobno ale w obu sytuacjach kod przestaje działać i wyrzuca błąd.
Mógłbyś krok po kroku opisać jak to połączyć z resztą kodu?

Z góry dzięki :)

**Comment by rafal-krypa** [comment]
@mikebike87 Jeśli dobrze rozumiem, to próbujesz użyć tokenów z dokumentacji - to tylko przykłady, nie będą działać. Potrzebujesz najpierw założyć konto na [pushover.net](https://pushover.net/), wygenerować własne tokeny i zainstalować aplikację na telefonie. 
Alternatywnie mogę zasugerować [pushbullet.com](https://www.pushbullet.com/), którego obsługa została niedawno dodana. Pushover daje 30 dni darmowego dostępu, a potem wymaga jednorazowej opłaty 5 USD. Pushbullet oferuje podstawowe konto bez żadnych opłat, ale za wersję Pro każe płacić miesięczny abonament. Ja akurat używam Pushbullet do tego typu zadań od 8 lat i wersja darmowa zawsze spełniała wszystkie moje potrzeby, ale w Twoim przypadku może oczywiście być inaczej.

PS.
Najwygodniej chyba będzie dodać ustawianie tych zmiennych do pliku `.env` w głównym katalogu medihunter:
```console
$ grep PUSHOVER .env
NOTIFIERS_PUSHOVER_USER=...
NOTIFIERS_PUSHOVER_TOKEN=...
```

**Comment by mikebike87** [comment]
@rafal-krypa dziękuję za pomoc :) właśnie o to mi chodziło, wpisanie kluczy do pliku .env rozwiązało mój problem (czemu od razu nie poszedłem najprostszą drogą...?) Całą resztę z rejestracją na pushover i kluczami USER i TOKEN ogarnąłem już wcześniej ale utknąłem na implementacji funkcji "export" w bashu a szukanie odpowiedzi w googlach o pythonie i bashu wcale nie rozjaśniało mi sytuacji.
Jeszcze raz dzięki za pomoc!
@apqlzm Dzięki za kod i całą instrukcję :) może dla takich jak ja amatorów warto dopisać przy powiadomieniach w Pushbullet/Pushover  w medihunter.py że klucze wystarczy dopisać do pliku  .env ;)
