### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by mflisiuk** [apqlzm/medihunter#5]
Cześć,

Pobrałem skrypt i podczas próby uruchomienia dostaję error. Czy masz może pomysł z czego wynika ten error?

Będę wdzięczny za pomoc

Dzięki!

> c:\Skrypty\Medihunter>medihunter find-appointment -r Warszawa -s 3
> User: ****
> Password:
> Logged in
> Traceback (most recent call last):
>   File "C:\Python\Scripts\medihunter-script.py", line 11, in <module>
>     load_entry_point('medihunter', 'console_scripts', 'medihunter')()
>   File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\skrypty\medihunter\medihunter.py", line 136, in find_appointment
>     service=service)
>   File "c:\skrypty\medihunter\medicover_session.py", line 219, in search_appointments
>     return self._parse_search_results(result)
>   File "c:\skrypty\medihunter\medicover_session.py", line 151, in _parse_search_results
>     result = result['items']
> KeyError: 'items'

**Comment by apqlzm** [comment]
Wygląda na to że zmienił się zestaw parametrów wyszukiwania wizyt na stronie Medicoveru. Postaram się niebawem wrzucić poprawkę.

**Comment by apqlzm** [comment]
Powinno już działać. 
BTW zamiast słowa Warszawa trzeba wpisać jej id czyli 204
