### ISSUE TITLE
Funkcja szukania po konketnej godzinie

### ISSUE THREAD

**Issue by bonk1990** [apqlzm/medihunter#9]
Czy jest taka możliwość by szukać wizyt np po godzinie 16?

**Comment by apqlzm** [comment]
Właśnie wypchnąłem zmiany które to umożliwą. Pojawiły się dwie dodatkowe opcje:
- -a, --start-time; domyślna wartość: "0:00"; (format: hh:mm)
- -g, --end-time; domyślna wartość: "23:59"; (format: hh:mm)
Czyli np. żeby wyszukać wizyty po godzinie 16 trzeba dodać opcję `-a "16:00"`

**Comment by bonk1990** [comment]
Jestem pod wrażeniem. Przetestuję w wolnej chwili.
